"""Complete action catalog for the Ozon Seller MCP server."""

from __future__ import annotations

from dataclasses import dataclass, field

from pydantic import BaseModel

from .models import (
    AnalyticsDataParams,
    AnalyticsItemTurnoverParams,
    AnalyticsStockParams,
    BarcodeAddParams,
    BrandListParams,
    CancellationApproveParams,
    CancellationIdParams,
    CancellationListParams,
    CategoryAttributesParams,
    CategoryAttributeValuesParams,
    CategoryAttributeValuesSearchParams,
    CategoryTreeParams,
    CertificateBindParams,
    CertificateCreateParams,
    CertificateIdParams,
    CertificateListParams,
    ChatHistoryParams,
    ChatListParams,
    ChatReadParams,
    ChatSendFileParams,
    ChatSendMessageParams,
    DeliveryMethodIdParams,
    DeliveryMethodsParams,
    FbsActCreateParams,
    FbsDigitalActParams,
    FbsLabelParams,
    FbsLastMileParams,
    FbsPostingCancelParams,
    FbsPostingsListParams,
    FbsPostingTrackingParams,
    FbsProductCountrySetParams,
    FboSupplyCreateParams,
    FilterLastIdLimitParams,
    FilterPageParams,
    FinanceCashFlowParams,
    FinanceRealizationParams,
    FinanceTotalsParams,
    FinanceTransactionsParams,
    IdParams,
    PostingNumberParams,
    ProductAttributesParams,
    ProductDescriptionParams,
    ProductDigitalCodesParams,
    ProductIdsParams,
    ProductImportParams,
    ProductInfoListParams,
    ProductInfoParams,
    ProductPicturesImportParams,
    ProductPricesUpdateParams,
    ProductRatingParams,
    ProductRelatedSkuParams,
    ProductStocksUpdateParams,
    PromoActionParams,
    PromoProductsAddParams,
    PromoProductsRemoveParams,
    QualityRatingParams,
    QuestionAnswerParams,
    QuestionsListParams,
    RatingHistoryParams,
    ReportCodeParams,
    ReportCreateParams,
    ReportListParams,
    ReturnApproveParams,
    ReturnCompensateParams,
    ReturnIdParams,
    ReturnRejectParams,
    ReturnsFilterParams,
    ReviewCommentParams,
    ReviewCountParams,
    ReviewIdParams,
    ReviewsListParams,
    StrategyCreateParams,
    StrategyIdParams,
    StrategyUpdateParams,
    SupplyOrderIdParams,
    TaskIdParams,
    WarehouseIdParams,
)


@dataclass(frozen=True, slots=True)
class Action:
    id: str
    domain: str
    description: str
    params_model: type[BaseModel] | None
    api_method: str
    is_destructive: bool = False
    is_file: bool = False
    keywords: list[str] = field(default_factory=list)


_ACTIONS_LIST: list[Action] = [
    # ── Products ─────────────────────────────────────────────────────────
    Action(
        id="product-import",
        domain="products",
        description="Import/create products",
        params_model=ProductImportParams,
        api_method="product_import",
        keywords=["import", "create", "товар", "создать"],
    ),
    Action(
        id="product-import-info",
        domain="products",
        description="Get product import task status",
        params_model=TaskIdParams,
        api_method="product_import_info",
        keywords=["import", "status", "импорт"],
    ),
    Action(
        id="product-info",
        domain="products",
        description="Get product details by offer_id, product_id or SKU",
        params_model=ProductInfoParams,
        api_method="product_info",
        keywords=["product", "info", "details", "товар", "информация"],
    ),
    Action(
        id="product-info-list",
        domain="products",
        description="Get details for multiple products",
        params_model=ProductInfoListParams,
        api_method="product_info_list",
        keywords=["product", "info", "list", "batch"],
    ),
    Action(
        id="product-list",
        domain="products",
        description="List products with filters",
        params_model=FilterLastIdLimitParams,
        api_method="product_list",
        keywords=["product", "list", "товары", "список"],
    ),
    Action(
        id="product-update",
        domain="products",
        description="Update product fields",
        params_model=ProductImportParams,
        api_method="product_update",
        keywords=["product", "update", "обновить"],
    ),
    Action(
        id="product-prices-update",
        domain="products",
        description="Update product prices",
        params_model=ProductPricesUpdateParams,
        api_method="product_prices_update",
        keywords=["price", "цена", "обновить"],
    ),
    Action(
        id="product-stocks-update",
        domain="products",
        description="Update FBS product stocks",
        params_model=ProductStocksUpdateParams,
        api_method="product_stocks_update",
        keywords=["stock", "остатки", "обновить"],
    ),
    Action(
        id="product-stocks-info",
        domain="products",
        description="Get product stock levels",
        params_model=FilterLastIdLimitParams,
        api_method="product_stocks_info",
        keywords=["stock", "остатки", "info"],
    ),
    Action(
        id="product-prices-info",
        domain="products",
        description="Get product price information",
        params_model=FilterLastIdLimitParams,
        api_method="product_prices_info",
        keywords=["price", "цена", "info"],
    ),
    Action(
        id="product-description",
        domain="products",
        description="Get product description",
        params_model=ProductDescriptionParams,
        api_method="product_description",
        keywords=["description", "описание"],
    ),
    Action(
        id="product-attributes",
        domain="products",
        description="Get product attributes",
        params_model=ProductAttributesParams,
        api_method="product_attributes",
        keywords=["attributes", "атрибуты"],
    ),
    Action(
        id="product-archive",
        domain="products",
        description="Archive products",
        params_model=ProductIdsParams,
        api_method="product_archive",
        is_destructive=True,
        keywords=["archive", "архив"],
    ),
    Action(
        id="product-unarchive",
        domain="products",
        description="Unarchive products",
        params_model=ProductIdsParams,
        api_method="product_unarchive",
        keywords=["unarchive", "разархивировать"],
    ),
    Action(
        id="product-delete",
        domain="products",
        description="Delete products permanently",
        params_model=ProductIdsParams,
        api_method="product_delete",
        is_destructive=True,
        keywords=["delete", "удалить"],
    ),
    Action(
        id="product-pictures-import",
        domain="products",
        description="Import product images",
        params_model=ProductPicturesImportParams,
        api_method="product_pictures_import",
        keywords=["pictures", "images", "фото", "изображения"],
    ),
    Action(
        id="product-pictures-info",
        domain="products",
        description="Get product image upload status",
        params_model=ProductIdsParams,
        api_method="product_pictures_info",
        keywords=["pictures", "images", "status"],
    ),
    Action(
        id="product-geo-restrictions",
        domain="products",
        description="Get product geo restrictions",
        params_model=FilterLastIdLimitParams,
        api_method="product_geo_restrictions",
        keywords=["geo", "restrictions", "ограничения"],
    ),
    Action(
        id="product-rating",
        domain="products",
        description="Get content rating by SKU",
        params_model=ProductRatingParams,
        api_method="product_rating",
        keywords=["rating", "рейтинг", "контент"],
    ),
    Action(
        id="product-related-sku",
        domain="products",
        description="Get related SKUs (FBO/FBS)",
        params_model=ProductRelatedSkuParams,
        api_method="product_related_sku",
        keywords=["related", "sku", "связанные"],
    ),
    Action(
        id="product-digital-codes",
        domain="products",
        description="Upload digital activation codes",
        params_model=ProductDigitalCodesParams,
        api_method="product_upload_digital_codes",
        keywords=["digital", "codes", "цифровые коды"],
    ),
    # ── FBS ───────────────────────────────────────────────────────────────
    Action(
        id="fbs-postings-list",
        domain="fbs",
        description="List FBS postings with filters",
        params_model=FbsPostingsListParams,
        api_method="fbs_postings_list",
        keywords=["fbs", "postings", "list", "отправления"],
    ),
    Action(
        id="fbs-posting-get",
        domain="fbs",
        description="Get FBS posting details",
        params_model=PostingNumberParams,
        api_method="fbs_posting_get",
        keywords=["fbs", "posting", "details", "отправление"],
    ),
    Action(
        id="fbs-posting-cancel",
        domain="fbs",
        description="Cancel FBS posting",
        params_model=FbsPostingCancelParams,
        api_method="fbs_posting_cancel",
        is_destructive=True,
        keywords=["fbs", "cancel", "отмена"],
    ),
    Action(
        id="fbs-cancel-reasons",
        domain="fbs",
        description="List FBS cancellation reasons",
        params_model=None,
        api_method="fbs_cancel_reasons",
        keywords=["fbs", "cancel", "reasons", "причины"],
    ),
    Action(
        id="fbs-posting-tracking",
        domain="fbs",
        description="Set tracking number for FBS posting",
        params_model=FbsPostingTrackingParams,
        api_method="fbs_posting_tracking",
        keywords=["fbs", "tracking", "трек"],
    ),
    Action(
        id="fbs-label-pdf",
        domain="fbs",
        description="Download FBS package label PDF",
        params_model=FbsLabelParams,
        api_method="get_label_pdf",
        is_file=True,
        keywords=["fbs", "label", "pdf", "этикетка"],
    ),
    Action(
        id="fbs-act-create",
        domain="fbs",
        description="Create shipping act",
        params_model=FbsActCreateParams,
        api_method="fbs_act_create",
        keywords=["fbs", "act", "акт", "создать"],
    ),
    Action(
        id="fbs-act-status",
        domain="fbs",
        description="Check act generation status",
        params_model=IdParams,
        api_method="fbs_act_status",
        keywords=["fbs", "act", "status", "статус"],
    ),
    Action(
        id="fbs-act-pdf",
        domain="fbs",
        description="Download shipping act PDF",
        params_model=IdParams,
        api_method="fbs_act_pdf",
        is_file=True,
        keywords=["fbs", "act", "pdf", "скачать"],
    ),
    Action(
        id="fbs-digital-act-pdf",
        domain="fbs",
        description="Download digital act PDF",
        params_model=FbsDigitalActParams,
        api_method="fbs_digital_act_pdf",
        is_file=True,
        keywords=["fbs", "digital", "act", "pdf", "электронный"],
    ),
    Action(
        id="fbs-container-labels",
        domain="fbs",
        description="Download container labels",
        params_model=IdParams,
        api_method="fbs_container_labels",
        is_file=True,
        keywords=["fbs", "container", "labels", "контейнер"],
    ),
    Action(
        id="fbs-posting-delivered",
        domain="fbs",
        description="Confirm FBS posting delivery (rFBS)",
        params_model=PostingNumberParams,
        api_method="fbs_posting_delivered",
        keywords=["fbs", "delivered", "доставлено"],
    ),
    Action(
        id="fbs-posting-last-mile",
        domain="fbs",
        description="Ship last mile",
        params_model=FbsLastMileParams,
        api_method="fbs_posting_last_mile",
        keywords=["fbs", "last mile", "последняя миля"],
    ),
    Action(
        id="fbs-timeslot-restrictions",
        domain="fbs",
        description="Get timeslot change restrictions",
        params_model=DeliveryMethodIdParams,
        api_method="fbs_timeslot_restrictions",
        keywords=["fbs", "timeslot", "таймслот"],
    ),
    Action(
        id="fbs-restrictions",
        domain="fbs",
        description="Get posting restrictions",
        params_model=PostingNumberParams,
        api_method="fbs_restrictions",
        keywords=["fbs", "restrictions", "ограничения"],
    ),
    Action(
        id="fbs-product-country-set",
        domain="fbs",
        description="Set product country of origin",
        params_model=FbsProductCountrySetParams,
        api_method="fbs_product_country_set",
        keywords=["fbs", "country", "страна"],
    ),
    Action(
        id="fbs-product-country-list",
        domain="fbs",
        description="List countries of origin",
        params_model=None,
        api_method="fbs_product_country_list",
        keywords=["fbs", "country", "list", "страны"],
    ),
    # ── FBO ───────────────────────────────────────────────────────────────
    Action(
        id="fbo-postings-list",
        domain="fbo",
        description="List FBO postings with filters",
        params_model=FbsPostingsListParams,
        api_method="fbo_postings_list",
        keywords=["fbo", "postings", "list", "отправления"],
    ),
    Action(
        id="fbo-posting-get",
        domain="fbo",
        description="Get FBO posting details",
        params_model=PostingNumberParams,
        api_method="fbo_posting_get",
        keywords=["fbo", "posting", "details", "отправление"],
    ),
    Action(
        id="fbo-supply-create",
        domain="fbo",
        description="Create FBO supply order",
        params_model=FboSupplyCreateParams,
        api_method="fbo_supply_create",
        keywords=["fbo", "supply", "create", "поставка", "создать"],
    ),
    Action(
        id="fbo-supply-get",
        domain="fbo",
        description="Get FBO supply order details",
        params_model=SupplyOrderIdParams,
        api_method="fbo_supply_get",
        keywords=["fbo", "supply", "get", "поставка"],
    ),
    Action(
        id="fbo-supply-list",
        domain="fbo",
        description="List FBO supply orders",
        params_model=FilterPageParams,
        api_method="fbo_supply_list",
        keywords=["fbo", "supply", "list", "поставки"],
    ),
    Action(
        id="fbo-supply-cancel",
        domain="fbo",
        description="Cancel FBO supply order",
        params_model=SupplyOrderIdParams,
        api_method="fbo_supply_cancel",
        is_destructive=True,
        keywords=["fbo", "supply", "cancel", "отмена"],
    ),
    Action(
        id="fbo-supply-items",
        domain="fbo",
        description="Get FBO supply order items",
        params_model=SupplyOrderIdParams,
        api_method="fbo_supply_items",
        keywords=["fbo", "supply", "items", "товары"],
    ),
    Action(
        id="fbo-supply-shipments",
        domain="fbo",
        description="Get FBO supply shipments",
        params_model=SupplyOrderIdParams,
        api_method="fbo_supply_shipments",
        keywords=["fbo", "supply", "shipments", "отгрузки"],
    ),
    Action(
        id="fbo-warehouse-workload",
        domain="fbo",
        description="Get FBO warehouse workload",
        params_model=WarehouseIdParams,
        api_method="fbo_warehouse_workload",
        keywords=["fbo", "warehouse", "workload", "загрузка", "склад"],
    ),
    # ── Categories ────────────────────────────────────────────────────────
    Action(
        id="category-tree",
        domain="categories",
        description="Get category tree",
        params_model=CategoryTreeParams,
        api_method="category_tree",
        keywords=["category", "tree", "категории", "дерево"],
    ),
    Action(
        id="category-attributes",
        domain="categories",
        description="Get category attributes",
        params_model=CategoryAttributesParams,
        api_method="category_attributes",
        keywords=["category", "attributes", "атрибуты"],
    ),
    Action(
        id="category-attribute-values",
        domain="categories",
        description="Get attribute values for a category",
        params_model=CategoryAttributeValuesParams,
        api_method="category_attribute_values",
        keywords=["category", "attribute", "values", "значения"],
    ),
    Action(
        id="category-attribute-values-search",
        domain="categories",
        description="Search attribute values in a category",
        params_model=CategoryAttributeValuesSearchParams,
        api_method="category_attribute_values_search",
        keywords=["category", "attribute", "search", "поиск"],
    ),
    # ── Finance ───────────────────────────────────────────────────────────
    Action(
        id="finance-transactions",
        domain="finance",
        description="Get finance transactions",
        params_model=FinanceTransactionsParams,
        api_method="finance_transactions",
        keywords=["finance", "transactions", "финансы", "транзакции"],
    ),
    Action(
        id="finance-totals",
        domain="finance",
        description="Get finance totals",
        params_model=FinanceTotalsParams,
        api_method="finance_totals",
        keywords=["finance", "totals", "итоги"],
    ),
    Action(
        id="finance-cash-flow",
        domain="finance",
        description="Get cash flow statement",
        params_model=FinanceCashFlowParams,
        api_method="finance_cash_flow",
        keywords=["finance", "cash", "flow", "денежный поток"],
    ),
    Action(
        id="finance-realization",
        domain="finance",
        description="Get realization report",
        params_model=FinanceRealizationParams,
        api_method="finance_realization",
        keywords=["finance", "realization", "реализация"],
    ),
    # ── Analytics ─────────────────────────────────────────────────────────
    Action(
        id="analytics-data",
        domain="analytics",
        description="Get analytics data",
        params_model=AnalyticsDataParams,
        api_method="analytics_data",
        keywords=["analytics", "data", "аналитика", "данные"],
    ),
    Action(
        id="analytics-stock",
        domain="analytics",
        description="Get stock analytics on warehouses",
        params_model=AnalyticsStockParams,
        api_method="analytics_stock_on_warehouses",
        keywords=["analytics", "stock", "warehouses", "остатки", "склады"],
    ),
    Action(
        id="analytics-turnover",
        domain="analytics",
        description="Get item turnover analytics",
        params_model=AnalyticsItemTurnoverParams,
        api_method="analytics_item_turnover",
        keywords=["analytics", "turnover", "оборачиваемость"],
    ),
    # ── Warehouses ────────────────────────────────────────────────────────
    Action(
        id="warehouse-list",
        domain="warehouses",
        description="List seller warehouses",
        params_model=None,
        api_method="warehouse_list",
        keywords=["warehouse", "list", "склады", "список"],
    ),
    Action(
        id="delivery-methods",
        domain="warehouses",
        description="Get delivery methods",
        params_model=DeliveryMethodsParams,
        api_method="delivery_methods",
        keywords=["delivery", "methods", "доставка", "методы"],
    ),
    # ── Returns ───────────────────────────────────────────────────────────
    Action(
        id="returns-fbo",
        domain="returns",
        description="Get FBO returns",
        params_model=ReturnsFilterParams,
        api_method="returns_fbo",
        keywords=["returns", "fbo", "возвраты"],
    ),
    Action(
        id="returns-fbs",
        domain="returns",
        description="Get FBS returns",
        params_model=ReturnsFilterParams,
        api_method="returns_fbs",
        keywords=["returns", "fbs", "возвраты"],
    ),
    Action(
        id="return-get",
        domain="returns",
        description="Get return details by posting number",
        params_model=PostingNumberParams,
        api_method="return_get",
        keywords=["return", "get", "возврат"],
    ),
    Action(
        id="return-rfbs-list",
        domain="returns",
        description="List rFBS returns",
        params_model=ReturnsFilterParams,
        api_method="return_rfbs_list",
        keywords=["return", "rfbs", "list", "возвраты"],
    ),
    Action(
        id="return-rfbs-get",
        domain="returns",
        description="Get rFBS return details",
        params_model=ReturnIdParams,
        api_method="return_rfbs_get",
        keywords=["return", "rfbs", "get", "возврат"],
    ),
    Action(
        id="return-rfbs-approve",
        domain="returns",
        description="Approve rFBS return",
        params_model=ReturnApproveParams,
        api_method="return_rfbs_approve",
        keywords=["return", "rfbs", "approve", "одобрить"],
    ),
    Action(
        id="return-rfbs-reject",
        domain="returns",
        description="Reject rFBS return",
        params_model=ReturnRejectParams,
        api_method="return_rfbs_reject",
        is_destructive=True,
        keywords=["return", "rfbs", "reject", "отклонить"],
    ),
    Action(
        id="return-rfbs-compensate",
        domain="returns",
        description="Compensate rFBS return",
        params_model=ReturnCompensateParams,
        api_method="return_rfbs_compensate",
        keywords=["return", "rfbs", "compensate", "компенсация"],
    ),
    # ── Chats ─────────────────────────────────────────────────────────────
    Action(
        id="chat-list",
        domain="chats",
        description="List chats",
        params_model=ChatListParams,
        api_method="chat_list",
        keywords=["chat", "list", "чаты", "список"],
    ),
    Action(
        id="chat-history",
        domain="chats",
        description="Get chat message history",
        params_model=ChatHistoryParams,
        api_method="chat_history",
        keywords=["chat", "history", "история", "сообщения"],
    ),
    Action(
        id="chat-start",
        domain="chats",
        description="Start a new chat by posting number",
        params_model=PostingNumberParams,
        api_method="chat_start",
        keywords=["chat", "start", "начать", "создать"],
    ),
    Action(
        id="chat-send-message",
        domain="chats",
        description="Send a message in chat",
        params_model=ChatSendMessageParams,
        api_method="chat_send_message",
        keywords=["chat", "send", "message", "отправить", "сообщение"],
    ),
    Action(
        id="chat-send-file",
        domain="chats",
        description="Send a file in chat",
        params_model=ChatSendFileParams,
        api_method="chat_send_file",
        keywords=["chat", "send", "file", "файл"],
    ),
    Action(
        id="chat-read",
        domain="chats",
        description="Mark chat messages as read",
        params_model=ChatReadParams,
        api_method="chat_read",
        keywords=["chat", "read", "прочитать"],
    ),
    # ── Promos ────────────────────────────────────────────────────────────
    Action(
        id="promo-available",
        domain="promos",
        description="List available promotions",
        params_model=None,
        api_method="promo_available",
        keywords=["promo", "available", "акции", "доступные"],
    ),
    Action(
        id="promo-candidates",
        domain="promos",
        description="Get promo candidate products",
        params_model=PromoActionParams,
        api_method="promo_candidates",
        keywords=["promo", "candidates", "кандидаты"],
    ),
    Action(
        id="promo-products",
        domain="promos",
        description="Get products in a promotion",
        params_model=PromoActionParams,
        api_method="promo_products",
        keywords=["promo", "products", "товары"],
    ),
    Action(
        id="promo-products-add",
        domain="promos",
        description="Add products to a promotion",
        params_model=PromoProductsAddParams,
        api_method="promo_products_add",
        keywords=["promo", "add", "добавить"],
    ),
    Action(
        id="promo-products-remove",
        domain="promos",
        description="Remove products from a promotion",
        params_model=PromoProductsRemoveParams,
        api_method="promo_products_remove",
        is_destructive=True,
        keywords=["promo", "remove", "удалить"],
    ),
    Action(
        id="promo-hotsale-list",
        domain="promos",
        description="List hot sale promotions",
        params_model=None,
        api_method="promo_hotsale_list",
        keywords=["promo", "hotsale", "распродажа"],
    ),
    # ── Strategies ────────────────────────────────────────────────────────
    Action(
        id="strategy-list",
        domain="strategies",
        description="List pricing strategies",
        params_model=None,
        api_method="strategy_list",
        keywords=["strategy", "list", "стратегии", "список"],
    ),
    Action(
        id="strategy-create",
        domain="strategies",
        description="Create a pricing strategy",
        params_model=StrategyCreateParams,
        api_method="strategy_create",
        keywords=["strategy", "create", "стратегия", "создать"],
    ),
    Action(
        id="strategy-update",
        domain="strategies",
        description="Update a pricing strategy",
        params_model=StrategyUpdateParams,
        api_method="strategy_update",
        keywords=["strategy", "update", "обновить"],
    ),
    Action(
        id="strategy-delete",
        domain="strategies",
        description="Delete a pricing strategy",
        params_model=StrategyIdParams,
        api_method="strategy_delete",
        is_destructive=True,
        keywords=["strategy", "delete", "удалить"],
    ),
    # ── Rating ────────────────────────────────────────────────────────────
    Action(
        id="rating-summary",
        domain="rating",
        description="Get seller rating summary",
        params_model=None,
        api_method="rating_summary",
        keywords=["rating", "summary", "рейтинг", "сводка"],
    ),
    Action(
        id="rating-history",
        domain="rating",
        description="Get seller rating history",
        params_model=RatingHistoryParams,
        api_method="rating_history",
        keywords=["rating", "history", "рейтинг", "история"],
    ),
    Action(
        id="quality-rating",
        domain="rating",
        description="Get product quality rating",
        params_model=QualityRatingParams,
        api_method="quality_rating",
        keywords=["quality", "rating", "качество", "рейтинг"],
    ),
    # ── Reports ───────────────────────────────────────────────────────────
    Action(
        id="report-create",
        domain="reports",
        description="Create a report",
        params_model=ReportCreateParams,
        api_method="report_create",
        keywords=["report", "create", "отчёт", "создать"],
    ),
    Action(
        id="report-info",
        domain="reports",
        description="Get report generation status",
        params_model=ReportCodeParams,
        api_method="report_info",
        keywords=["report", "info", "status", "статус"],
    ),
    Action(
        id="report-list",
        domain="reports",
        description="List reports",
        params_model=ReportListParams,
        api_method="report_list",
        keywords=["report", "list", "отчёты", "список"],
    ),
    Action(
        id="report-download",
        domain="reports",
        description="Download report file",
        params_model=ReportCodeParams,
        api_method="report_download",
        is_file=True,
        keywords=["report", "download", "скачать"],
    ),
    # ── Reviews ───────────────────────────────────────────────────────────
    Action(
        id="reviews-list",
        domain="reviews",
        description="List product reviews",
        params_model=ReviewsListParams,
        api_method="reviews_list",
        keywords=["reviews", "list", "отзывы", "список"],
    ),
    Action(
        id="review-info",
        domain="reviews",
        description="Get review details",
        params_model=ReviewIdParams,
        api_method="review_info",
        keywords=["review", "info", "отзыв"],
    ),
    Action(
        id="review-count",
        domain="reviews",
        description="Get review count",
        params_model=ReviewCountParams,
        api_method="review_count",
        keywords=["review", "count", "количество"],
    ),
    Action(
        id="review-comment",
        domain="reviews",
        description="Post a comment on a review",
        params_model=ReviewCommentParams,
        api_method="review_comment",
        keywords=["review", "comment", "комментарий"],
    ),
    # ── Questions ─────────────────────────────────────────────────────────
    Action(
        id="questions-list",
        domain="questions",
        description="List product questions",
        params_model=QuestionsListParams,
        api_method="questions_list",
        keywords=["questions", "list", "вопросы", "список"],
    ),
    Action(
        id="question-answer",
        domain="questions",
        description="Answer a product question",
        params_model=QuestionAnswerParams,
        api_method="question_answer",
        keywords=["question", "answer", "ответ"],
    ),
    Action(
        id="question-update",
        domain="questions",
        description="Update an answer to a question",
        params_model=QuestionAnswerParams,
        api_method="question_update",
        keywords=["question", "update", "обновить"],
    ),
    # ── Cancellations ─────────────────────────────────────────────────────
    Action(
        id="cancellation-list",
        domain="cancellations",
        description="List cancellation requests",
        params_model=CancellationListParams,
        api_method="cancellation_list",
        keywords=["cancellation", "list", "отмены", "список"],
    ),
    Action(
        id="cancellation-info",
        domain="cancellations",
        description="Get cancellation request details",
        params_model=CancellationIdParams,
        api_method="cancellation_info",
        keywords=["cancellation", "info", "отмена"],
    ),
    Action(
        id="cancellation-approve",
        domain="cancellations",
        description="Approve cancellation request",
        params_model=CancellationApproveParams,
        api_method="cancellation_approve",
        keywords=["cancellation", "approve", "одобрить"],
    ),
    Action(
        id="cancellation-reject",
        domain="cancellations",
        description="Reject cancellation request",
        params_model=CancellationApproveParams,
        api_method="cancellation_reject",
        keywords=["cancellation", "reject", "отклонить"],
    ),
    # ── Certificates ──────────────────────────────────────────────────────
    Action(
        id="certificate-list",
        domain="certificates",
        description="List certificates",
        params_model=CertificateListParams,
        api_method="certificate_list",
        keywords=["certificate", "list", "сертификаты", "список"],
    ),
    Action(
        id="certificate-info",
        domain="certificates",
        description="Get certificate details",
        params_model=CertificateIdParams,
        api_method="certificate_info",
        keywords=["certificate", "info", "сертификат"],
    ),
    Action(
        id="certificate-create",
        domain="certificates",
        description="Create a certificate",
        params_model=CertificateCreateParams,
        api_method="certificate_create",
        keywords=["certificate", "create", "сертификат", "создать"],
    ),
    Action(
        id="certificate-delete",
        domain="certificates",
        description="Delete a certificate",
        params_model=CertificateIdParams,
        api_method="certificate_delete",
        is_destructive=True,
        keywords=["certificate", "delete", "удалить"],
    ),
    Action(
        id="certificate-bind",
        domain="certificates",
        description="Bind certificate to products",
        params_model=CertificateBindParams,
        api_method="certificate_bind",
        keywords=["certificate", "bind", "привязать"],
    ),
    Action(
        id="certificate-unbind",
        domain="certificates",
        description="Unbind certificate from products",
        params_model=CertificateBindParams,
        api_method="certificate_unbind",
        keywords=["certificate", "unbind", "отвязать"],
    ),
    # ── Barcodes ──────────────────────────────────────────────────────────
    Action(
        id="barcode-generate",
        domain="barcodes",
        description="Generate barcodes for products",
        params_model=ProductIdsParams,
        api_method="barcode_generate",
        keywords=["barcode", "generate", "штрихкод", "сгенерировать"],
    ),
    Action(
        id="barcode-add",
        domain="barcodes",
        description="Add barcodes to products",
        params_model=BarcodeAddParams,
        api_method="barcode_add",
        keywords=["barcode", "add", "штрихкод", "добавить"],
    ),
    # ── Brands ────────────────────────────────────────────────────────────
    Action(
        id="brand-list",
        domain="brands",
        description="List brands",
        params_model=BrandListParams,
        api_method="brand_list",
        keywords=["brand", "list", "бренды", "список"],
    ),
]

ACTIONS: dict[str, Action] = {a.id: a for a in _ACTIONS_LIST}
